### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CaptDedEyes** [pharanbrush/animators_gif_enjoyer#1]
The only feature I would like to suggest is to save the window size whenever the app is closed and later reopened. Windows Photo Viewer does this, as do many other Windows applications, so this would be an excellent quality-of-life feature, especially whenever I open GIFs of varying sizes.

**Comment by pharanbrush** [comment]
Yeah, persisting the window size was actually on the list. But it didn't make the cut because I wasn't sure if it was desirable to just have it become giant again after previously opening a giant gif.

I need to look into what a good behavior would be like.
But I suppose I could just make it an opt-in thing since I did the same with multiple windows.

It makes me a bit nervous to add it because I don't know how to account for if the monitor setup changes between launches.

**Comment by CaptDedEyes** [comment]
Yea, that would be a great idea! Just stick in the Advanced options.
